services:
  oafse-redis:
    image: redis:alpine
    container_name: oafse_redis
    ports:
      - 6379:6379
    networks:
      - oafse-net

  oafse-postgres:
    image: postgres:18-alpine
    container_name: oafse_postgres
    env_file: ".env"
    ports:
      - 5432:5432
    networks:
      - oafse-net
    volumes:
      - oafse-db:/var/lib/postgresql

networks:
  oafse-net:

volumes:
  oafse-db:
