services:
  oafse-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: oafse-server
    env_file: ".env"
    ports:
      - 14444:14444
      - 9100:9100
    environment:
      POSTGRES_DSN: ${POSTGRES_DOCKER_DSN}
      EMBEDDER_URL: ${EMBEDDER_DOCKER_URL}
      SERVER_ADDR: ${SERVER_ADDR}
      METRICS_ADDR: ${METRICS_ADDR}
    networks:
      - oafse-net
    depends_on:
      oafse-embedder:
        condition: service_healthy
      oafse-postgres:
        condition: service_healthy

  oafse-crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    container_name: oafse-crawler
    env_file: ".env"
    ports:
      - 9101:9100
      - 14443:14443
    environment:
      POSTGRES_DSN: ${POSTGRES_DOCKER_DSN}
      REDIS_DSN: ${REDIS_DOCKER_DSN}
      METRICS_ADDR: ${METRICS_ADDR}
      CRAWLER_ADDR: ${CRAWLER_ADDR}
    networks:
      - oafse-net
    depends_on:
      oafse-redis:
        condition: service_started
      oafse-postgres:
        condition: service_healthy
      oafse-indexer:
        condition: service_started

  oafse-indexer:
    build:
      context: .
      dockerfile: Dockerfile.indexer
    container_name: oafse-indexer
    env_file: ".env"
    ports:
      - 9102:9100
    environment:
      POSTGRES_DSN: ${POSTGRES_DOCKER_DSN}
      REDIS_DSN: ${REDIS_DOCKER_DSN}
      EMBEDDER_URL: ${EMBEDDER_DOCKER_URL}
      METRICS_ADDR: ${METRICS_ADDR}
    networks:
      - oafse-net
    depends_on:
      oafse-postgres:
        condition: service_healthy
      oafse-redis:
        condition: service_started
      oafse-embedder:
        condition: service_healthy

  oafse-embedder:
    build:
      context: ./embedder
      dockerfile: Dockerfile.embedder
    container_name: oafse-embedder
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/14445'"]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      EMBEDDER_ADDR: ${EMBEDDER_ADDR}
    ports:
      - 14445:14445
    networks:
      - oafse-net

  oafse-redis:
    image: redis:alpine
    container_name: oafse_redis
    ports:
      - 6379:6379
    networks:
      - oafse-net

  oafse-postgres:
    image: pgvector/pgvector:pg18
    container_name: oafse_postgres
    env_file: ".env"
    ports:
      - 5432:5432
    networks:
      - oafse-net
    volumes:
      - oafse-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      start_period: 30s
      timeout: 5s
      retries: 5

  oafse-prometheus:
    image: prom/prometheus:latest
    container_name: oafse_prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - oafse-prometheus-data:/prometheus
    ports:
      - 9090:9090
    networks:
      - oafse-net
    depends_on:
      - oafse-server
      - oafse-crawler
      - oafse-indexer

  oafse-grafana:
    image: grafana/grafana:latest
    container_name: oafse_grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - oafse-grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - oafse-net
    depends_on:
      - oafse-prometheus

networks:
  oafse-net:

volumes:
  oafse-db:
  oafse-prometheus-data:
  oafse-grafana-data:
