FROM golang:1.26-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o indexer ./cmd/indexer

FROM alpine:latest

RUN apk add --no-cache ca-certificates

RUN adduser -D -u 10001 indexeruser
WORKDIR /app

COPY --from=builder --chown=indexeruser:indexeruser /app/indexer .

USER 10001:10001
ENTRYPOINT ["/app/indexer"]
