FROM golang:1.26-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY . .

RUN swag init -g main.go -d ./cmd/crawler,./internal/delivery/http/handler/crawl,./internal/delivery/http/json -o docs/crawler
RUN CGO_ENABLED=0 go build -o crawler ./cmd/crawler
RUN chmod +x /app/crawler

FROM alpine:latest

RUN apk add --no-cache \
    chromium \
    harfbuzz \
    nss \
    freetype \
    ttf-freefont \
    font-noto \
    ca-certificates \
    dbus

RUN adduser -D -u 10001 crawleruser
WORKDIR /app

COPY --from=builder --chown=crawleruser:crawleruser /app/crawler .

USER 10001:10001
ENTRYPOINT ["/app/crawler"]
