services:
  oafse-crawler:
    build: .
    container_name: oafse-crawler
    env_file: ".env"
    environment:
      POSTGRES_DSN: ${POSTGRES_DOCKER_DSN}
      REDIS_DSN: ${REDIS_DOCKER_DSN}
    ports:
      - 14444:14444
    networks:
      - oafse-net
    depends_on:
      oafse-redis:
        condition: service_started
      oafse-postgres:
        condition: service_healthy
  oafse-redis:
    image: redis:alpine
    container_name: oafse_redis
    ports:
      - 6379:6379
    networks:
      - oafse-net

  oafse-postgres:
    image: postgres:18-alpine
    container_name: oafse_postgres
    env_file: ".env"
    ports:
      - 5432:5432
    networks:
      - oafse-net
    volumes:
      - oafse-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      start_period: 30s
      timeout: 5s
      retries: 5

networks:
  oafse-net:

volumes:
  oafse-db:
