# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedder.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'embedder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mbedder.proto\x12\x08\x65mbedder\"\x1c\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1f\n\rEmbedResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"\"\n\x11\x45mbedBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"7\n\x12\x45mbedBatchResponse\x12!\n\x07vectors\x18\x01 \x03(\x0b\x32\x10.embedder.Vector\"\x18\n\x06Vector\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32\x8d\x01\n\x08\x45mbedder\x12\x38\n\x05\x45mbed\x12\x16.embedder.EmbedRequest\x1a\x17.embedder.EmbedResponse\x12G\n\nEmbedBatch\x12\x1b.embedder.EmbedBatchRequest\x1a\x1c.embedder.EmbedBatchResponseB\x1aZ\x18oafse/pkg/proto/embedderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030oafse/pkg/proto/embedder'
  _globals['_EMBEDREQUEST']._serialized_start=28
  _globals['_EMBEDREQUEST']._serialized_end=56
  _globals['_EMBEDRESPONSE']._serialized_start=58
  _globals['_EMBEDRESPONSE']._serialized_end=89
  _globals['_EMBEDBATCHREQUEST']._serialized_start=91
  _globals['_EMBEDBATCHREQUEST']._serialized_end=125
  _globals['_EMBEDBATCHRESPONSE']._serialized_start=127
  _globals['_EMBEDBATCHRESPONSE']._serialized_end=182
  _globals['_VECTOR']._serialized_start=184
  _globals['_VECTOR']._serialized_end=208
  _globals['_EMBEDDER']._serialized_start=211
  _globals['_EMBEDDER']._serialized_end=352
# @@protoc_insertion_point(module_scope)
